### ISSUE TITLE
Async Task does not stop after Abort signal

### ISSUE THREAD

**Issue by vis-prime** [gkjohnson/three-edge-projection#36]
While using the generateAsync function, after the abort signal is sent 

`'ProjectionGenerator: Process aborted via AbortSignal.'` message is printed , 

but the task/req anim frame keeps on running.

Adding a `return` after the `reject()` in the generateAsync functions seems to fix the issue

**Comment by gkjohnson** [comment]
Oh thank you for the catch! Would you like to make a PR with the fix?

**Comment by vis-prime** [comment]
Sure !
